// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BattleLogTeamCardsItem
    {
        /// <summary>
        /// Initializes a new instance of the BattleLogTeamCardsItem class.
        /// </summary>
        public BattleLogTeamCardsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BattleLogTeamCardsItem class.
        /// </summary>
        public BattleLogTeamCardsItem(string name = default(string), int? level = default(int?), int? maxLevel = default(int?), CardIconUrls iconUrls = default(CardIconUrls))
        {
            Name = name;
            Level = level;
            MaxLevel = maxLevel;
            IconUrls = iconUrls;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "level")]
        public int? Level { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxLevel")]
        public int? MaxLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iconUrls")]
        public CardIconUrls IconUrls { get; set; }

    }
}
