// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClanBase
    {
        /// <summary>
        /// Initializes a new instance of the ClanBase class.
        /// </summary>
        public ClanBase()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClanBase class.
        /// </summary>
        public ClanBase(string tag = default(string), string name = default(string), int? badgeId = default(int?))
        {
            Tag = tag;
            Name = name;
            BadgeId = badgeId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "badgeId")]
        public int? BadgeId { get; set; }

    }
}
