// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClanRankingListItemsItem
    {
        /// <summary>
        /// Initializes a new instance of the ClanRankingListItemsItem class.
        /// </summary>
        public ClanRankingListItemsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClanRankingListItemsItem class.
        /// </summary>
        public ClanRankingListItemsItem(string tag = default(string), string name = default(string), int? rank = default(int?), int? previousRank = default(int?), Location location = default(Location), int? clanScore = default(int?), int? badgeId = default(int?), int? members = default(int?))
        {
            Tag = tag;
            Name = name;
            Rank = rank;
            PreviousRank = previousRank;
            Location = location;
            ClanScore = clanScore;
            BadgeId = badgeId;
            Members = members;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rank")]
        public int? Rank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "previousRank")]
        public int? PreviousRank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public Location Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clanScore")]
        public int? ClanScore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "badgeId")]
        public int? BadgeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "members")]
        public int? Members { get; set; }

    }
}
