// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClanMember : PlayerBase
    {
        /// <summary>
        /// Initializes a new instance of the ClanMember class.
        /// </summary>
        public ClanMember()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClanMember class.
        /// </summary>
        public ClanMember(string tag = default(string), string name = default(string), int? expLevel = default(int?), int? trophies = default(int?), Arena arena = default(Arena), string role = default(string), int? clanRank = default(int?), int? previousClanRank = default(int?), int? donations = default(int?), int? donationsReceived = default(int?), int? clanChestPoints = default(int?))
            : base(tag, name, expLevel, trophies, arena)
        {
            Role = role;
            ClanRank = clanRank;
            PreviousClanRank = previousClanRank;
            Donations = donations;
            DonationsReceived = donationsReceived;
            ClanChestPoints = clanChestPoints;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "role")]
        public string Role { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clanRank")]
        public int? ClanRank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "previousClanRank")]
        public int? PreviousClanRank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "donations")]
        public int? Donations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "donationsReceived")]
        public int? DonationsReceived { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clanChestPoints")]
        public int? ClanChestPoints { get; set; }

    }
}
