// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PlayerDetailCurrentFavouriteCard
    {
        /// <summary>
        /// Initializes a new instance of the PlayerDetailCurrentFavouriteCard
        /// class.
        /// </summary>
        public PlayerDetailCurrentFavouriteCard()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlayerDetailCurrentFavouriteCard
        /// class.
        /// </summary>
        public PlayerDetailCurrentFavouriteCard(string name = default(string), int? id = default(int?), int? maxLevel = default(int?), PlayerDetailCurrentFavouriteCardIconUrls iconUrls = default(PlayerDetailCurrentFavouriteCardIconUrls))
        {
            Name = name;
            Id = id;
            MaxLevel = maxLevel;
            IconUrls = iconUrls;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxLevel")]
        public int? MaxLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iconUrls")]
        public PlayerDetailCurrentFavouriteCardIconUrls IconUrls { get; set; }

    }
}
