// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PlayerDetailCardsItem
    {
        /// <summary>
        /// Initializes a new instance of the PlayerDetailCardsItem class.
        /// </summary>
        public PlayerDetailCardsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlayerDetailCardsItem class.
        /// </summary>
        public PlayerDetailCardsItem(string name = default(string), int? level = default(int?), int? maxLevel = default(int?), int? count = default(int?), PlayerDetailCardsItemIconUrls iconUrls = default(PlayerDetailCardsItemIconUrls))
        {
            Name = name;
            Level = level;
            MaxLevel = maxLevel;
            Count = count;
            IconUrls = iconUrls;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "level")]
        public int? Level { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxLevel")]
        public int? MaxLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iconUrls")]
        public PlayerDetailCardsItemIconUrls IconUrls { get; set; }

        public override string ToString()
        {
            return $"{Name}={Level}";
        }

    }
}
