// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PlayerDetailCardsItemIconUrls
    {
        /// <summary>
        /// Initializes a new instance of the PlayerDetailCardsItemIconUrls
        /// class.
        /// </summary>
        public PlayerDetailCardsItemIconUrls()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlayerDetailCardsItemIconUrls
        /// class.
        /// </summary>
        public PlayerDetailCardsItemIconUrls(string medium = default(string))
        {
            Medium = medium;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "medium")]
        public string Medium { get; set; }

    }
}
