// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PlayerBase
    {
        /// <summary>
        /// Initializes a new instance of the PlayerBase class.
        /// </summary>
        public PlayerBase()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlayerBase class.
        /// </summary>
        public PlayerBase(string tag = default(string), string name = default(string), int? expLevel = default(int?), int? trophies = default(int?), Arena arena = default(Arena))
        {
            Tag = tag;
            Name = name;
            ExpLevel = expLevel;
            Trophies = trophies;
            Arena = arena;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expLevel")]
        public int? ExpLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trophies")]
        public int? Trophies { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "arena")]
        public Arena Arena { get; set; }

    }
}
