// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SearchResultClan : ClanBase
    {
        /// <summary>
        /// Initializes a new instance of the SearchResultClan class.
        /// </summary>
        public SearchResultClan()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SearchResultClan class.
        /// </summary>
        public SearchResultClan(string tag = default(string), string name = default(string), int? badgeId = default(int?), string type = default(string), int? clanScore = default(int?), int? requiredTrophies = default(int?), int? donationsPerWeek = default(int?), int? clanChestLevel = default(int?), int? clanChestMaxLevel = default(int?), int? members = default(int?), Location location = default(Location))
            : base(tag, name, badgeId)
        {
            Type = type;
            ClanScore = clanScore;
            RequiredTrophies = requiredTrophies;
            DonationsPerWeek = donationsPerWeek;
            ClanChestLevel = clanChestLevel;
            ClanChestMaxLevel = clanChestMaxLevel;
            Members = members;
            Location = location;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clanScore")]
        public int? ClanScore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requiredTrophies")]
        public int? RequiredTrophies { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "donationsPerWeek")]
        public int? DonationsPerWeek { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clanChestLevel")]
        public int? ClanChestLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clanChestMaxLevel")]
        public int? ClanChestMaxLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "members")]
        public int? Members { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public Location Location { get; set; }

        public override string ToString()
        {
            return $"{this.ClanScore}:{this.Name}";
        }

    }
}
