// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TournamentSearchResult : TournamentBase
    {
        /// <summary>
        /// Initializes a new instance of the TournamentSearchResult class.
        /// </summary>
        public TournamentSearchResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TournamentSearchResult class.
        /// </summary>
        public TournamentSearchResult(IList<TournamentBaseItemsItem> items = default(IList<TournamentBaseItemsItem>))
            : base(items)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
