// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpcomingChestsListItemsItem
    {
        /// <summary>
        /// Initializes a new instance of the UpcomingChestsListItemsItem
        /// class.
        /// </summary>
        public UpcomingChestsListItemsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpcomingChestsListItemsItem
        /// class.
        /// </summary>
        public UpcomingChestsListItemsItem(int? index = default(int?), string name = default(string))
        {
            Index = index;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "index")]
        public int? Index { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        public override string ToString()
        {
            return $"{Index.Value.ToString().PadLeft(4)} = {Name}";
        }

    }
}
