// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class VerifyTokenResponse
    {
        /// <summary>
        /// Initializes a new instance of the VerifyTokenResponse class.
        /// </summary>
        public VerifyTokenResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VerifyTokenResponse class.
        /// </summary>
        public VerifyTokenResponse(string tag = default(string), string token = default(string), string status = default(string))
        {
            Tag = tag;
            Token = token;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
