// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WarLog
    {
        /// <summary>
        /// Initializes a new instance of the WarLog class.
        /// </summary>
        public WarLog()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WarLog class.
        /// </summary>
        public WarLog(IList<WarLogItemsItem> items = default(IList<WarLogItemsItem>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<WarLogItemsItem> Items { get; set; }

    }
}
