// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyale.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WarLogItemsItem
    {
        /// <summary>
        /// Initializes a new instance of the WarLogItemsItem class.
        /// </summary>
        public WarLogItemsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WarLogItemsItem class.
        /// </summary>
        public WarLogItemsItem(int? seasonId = default(int?), string createdDate = default(string), IList<WarParticipant> participants = default(IList<WarParticipant>))
        {
            SeasonId = seasonId;
            CreatedDate = createdDate;
            Participants = participants;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seasonId")]
        public int? SeasonId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public string CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "participants")]
        public IList<WarParticipant> Participants { get; set; }

    }
}
