// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BattleLogTeam
    {
        /// <summary>
        /// Initializes a new instance of the BattleLogTeam class.
        /// </summary>
        public BattleLogTeam()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BattleLogTeam class.
        /// </summary>
        public BattleLogTeam(string tag = default(string), string name = default(string), int? startingTrophies = default(int?), int? trophyChange = default(int?), int? crowns = default(int?), ClanBase clan = default(ClanBase), IList<CardBattleLog> cards = default(IList<CardBattleLog>))
        {
            Tag = tag;
            Name = name;
            StartingTrophies = startingTrophies;
            TrophyChange = trophyChange;
            Crowns = crowns;
            Clan = clan;
            Cards = cards;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startingTrophies")]
        public int? StartingTrophies { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trophyChange")]
        public int? TrophyChange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crowns")]
        public int? Crowns { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clan")]
        public ClanBase Clan { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cards")]
        public IList<CardBattleLog> Cards { get; set; }

    }
}
