// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BattleLogItemGameMode
    {
        /// <summary>
        /// Initializes a new instance of the BattleLogItemGameMode class.
        /// </summary>
        public BattleLogItemGameMode()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BattleLogItemGameMode class.
        /// </summary>
        public BattleLogItemGameMode(int? id = default(int?), string name = default(string))
        {
            Id = id;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
