// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CardPlayer : CardBase
    {
        /// <summary>
        /// Initializes a new instance of the PlayerDetailCardsItem class.
        /// </summary>
        public CardPlayer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlayerDetailCardsItem class.
        /// </summary>
        public CardPlayer(string name = default(string), int? level = default(int?), int? maxLevel = default(int?), int? count = default(int?), CardIconUrls iconUrls = default(CardIconUrls))
            : base(name, null, maxLevel, iconUrls)
        {
            Level = level;
            IconUrls = iconUrls;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "level")]
        public int? Level { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        public override string ToString()
        {
            return $"{Name}={Level}";
        }

    }
}
