// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CardBattleLog : CardBase
    {
        /// <summary>
        /// Initializes a new instance of the BattleLogTeamCardsItem class.
        /// </summary>
        public CardBattleLog()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BattleLogTeamCardsItem class.
        /// </summary>
        public CardBattleLog(string name = default(string), int? level = default(int?), int? maxLevel = default(int?), CardIconUrls iconUrls = default(CardIconUrls))
            : base(name, null, maxLevel, iconUrls)
        {
            Level = level;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "level")]
        public int? Level { get; set; }

    }
}
