// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClanRankingList
    {
        /// <summary>
        /// Initializes a new instance of the ClanRankingList class.
        /// </summary>
        public ClanRankingList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClanRankingList class.
        /// </summary>
        public ClanRankingList(IList<ClanRanking> items = default(IList<ClanRanking>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<ClanRanking> Items { get; set; }

    }
}
