// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CurrentWarClan
    {
        /// <summary>
        /// Initializes a new instance of the CurrentWarClan class.
        /// </summary>
        public CurrentWarClan()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CurrentWarClan class.
        /// </summary>
        public CurrentWarClan(string tag = default(string), string name = default(string), int? badgeId = default(int?), int? clanScore = default(int?), int? participants = default(int?), int? battlesPlayed = default(int?), int? wins = default(int?), int? crowns = default(int?))
        {
            Tag = tag;
            Name = name;
            BadgeId = badgeId;
            ClanScore = clanScore;
            Participants = participants;
            BattlesPlayed = battlesPlayed;
            Wins = wins;
            Crowns = crowns;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "badgeId")]
        public int? BadgeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clanScore")]
        public int? ClanScore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "participants")]
        public int? Participants { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "battlesPlayed")]
        public int? BattlesPlayed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "wins")]
        public int? Wins { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crowns")]
        public int? Crowns { get; set; }

    }
}
