// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PlayerRanking : PlayerBase
    {
        /// <summary>
        /// Initializes a new instance of the PlayerRankingListItemsItem class.
        /// </summary>
        public PlayerRanking()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlayerRankingListItemsItem class.
        /// </summary>
        public PlayerRanking(string tag = default(string), string name = default(string), int? expLevel = default(int?), int? trophies = default(int?), int? rank = default(int?), int? previousRank = default(int?), ClanBase clan = default(ClanBase), Arena arena = default(Arena))
            : base(tag, name, expLevel, trophies, arena)
        {
            ExpLevel = expLevel;
            Trophies = trophies;
            Rank = rank;
            PreviousRank = previousRank;
            Clan = clan;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rank")]
        public int? Rank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "previousRank")]
        public int? PreviousRank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clan")]
        public ClanBase Clan { get; set; }
    }
}
