// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PlayerDetailAchievement
    {
        /// <summary>
        /// Initializes a new instance of the PlayerDetailAchievementsItem
        /// class.
        /// </summary>
        public PlayerDetailAchievement()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlayerDetailAchievementsItem
        /// class.
        /// </summary>
        public PlayerDetailAchievement(string name = default(string), int? stars = default(int?), int? value = default(int?), int? target = default(int?), string info = default(string))
        {
            Name = name;
            Stars = stars;
            Value = value;
            Target = target;
            Info = info;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stars")]
        public int? Stars { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public int? Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public int? Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "info")]
        public string Info { get; set; }

    }
}
