// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TournamentBase
    {
        /// <summary>
        /// Initializes a new instance of the TournamentBase class.
        /// </summary>
        public TournamentBase()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TournamentBase class.
        /// </summary>
        public TournamentBase(IList<TournamentItem> items = default(IList<TournamentItem>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<TournamentItem> Items { get; set; }

    }
}
