// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Tournament : TournamentBase
    {
        /// <summary>
        /// Initializes a new instance of the Tournament class.
        /// </summary>
        public Tournament()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Tournament class.
        /// </summary>
        public Tournament(IList<TournamentItem> items = default(IList<TournamentItem>), string startedTime = default(string), IList<TournamentMembersListItem> membersList = default(IList<TournamentMembersListItem>))
            : base(items)
        {
            StartedTime = startedTime;
            MembersList = membersList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startedTime")]
        public string StartedTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "membersList")]
        public IList<TournamentMembersListItem> MembersList { get; set; }

    }
}
