// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TournamentMembersListItem
    {
        /// <summary>
        /// Initializes a new instance of the TournamentMembersListItem class.
        /// </summary>
        public TournamentMembersListItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TournamentMembersListItem class.
        /// </summary>
        public TournamentMembersListItem(string tag = default(string), string name = default(string), int? score = default(int?), int? rank = default(int?), ClanBase clan = default(ClanBase))
        {
            Tag = tag;
            Name = name;
            Score = score;
            Rank = rank;
            Clan = clan;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public int? Score { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rank")]
        public int? Rank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clan")]
        public ClanBase Clan { get; set; }

    }
}
