// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClashRoyaleApi.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WarParticipant
    {
        /// <summary>
        /// Initializes a new instance of the WarParticipant class.
        /// </summary>
        public WarParticipant()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WarParticipant class.
        /// </summary>
        public WarParticipant(string tag = default(string), string name = default(string), int? cardsEarned = default(int?), int? battlesPlayed = default(int?), int? wins = default(int?))
        {
            Tag = tag;
            Name = name;
            CardsEarned = cardsEarned;
            BattlesPlayed = battlesPlayed;
            Wins = wins;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardsEarned")]
        public int? CardsEarned { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "battlesPlayed")]
        public int? BattlesPlayed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "wins")]
        public int? Wins { get; set; }

    }
}
